### ISSUE TITLE
Roadmap for V2

### ISSUE THREAD

**Issue by Kocal** [Kocal/jsdoc-vuejs#51]
It will do less things, but it will do them 100 times better.

### Features

- [x] Add tag `@vue.data`, e.g.: `/** @vue.data {String} foo - My foo data */`
- [x] Add tag `@vue.props`
- [x] Add tag `@vue.computed`

### Improvments

- [x] Better and cleaner source code
- [x] Cleaner tests
- [x] e2e tests with Cypress, to check if renderers work
- [x] Support default theme
- [x] Support [docstrap](https://github.com/docstrap/docstrap) theme
- [x] Support [tui](https://github.com/nhnent/tui.jsdoc-template) theme
- [x] Support [minami](https://github.com/nijikokun/minami) theme
- [x] Do something for #50 :thinking: 

### Removals

- [x] Remove `followImports` option
- [x] Remove all options, I don't think this plugin should be configurable
- [x] Remove Babel
- [x] Do not list lifecycle hooks, it's non-sense to document them

### Internals

- [x] Replace ESLint Standard config with AirBnB 
- [x] Update all dependencies
- [x] Remove branch `develop` 
- [x] Replace Coveralls by Codecov
- [x] Replace GPL3 license with MIT
- [x] Rewrite README (with screenshots, and codecov badge)
- [ ] Update `package.json` version
